// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSgMZUGmw__Dt2MReLb9fqgg3FB7-Rn8g',
    appId: '1:696339704648:web:f59270b0c936e1126d617d',
    messagingSenderId: '696339704648',
    projectId: 'sistema-pedidos-grupo5-2026',
    authDomain: 'sistema-pedidos-grupo5-2026.firebaseapp.com',
    storageBucket: 'sistema-pedidos-grupo5-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP-zgWWA1A00tDHrCn59rZUqEepZNneW8',
    appId: '1:696339704648:android:eabfcb162fa8a5f06d617d',
    messagingSenderId: '696339704648',
    projectId: 'sistema-pedidos-grupo5-2026',
    storageBucket: 'sistema-pedidos-grupo5-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1yeeHFaT39H6aq0uq-s1Oyvhls3phtUU',
    appId: '1:696339704648:ios:453ef53e0e9c03606d617d',
    messagingSenderId: '696339704648',
    projectId: 'sistema-pedidos-grupo5-2026',
    storageBucket: 'sistema-pedidos-grupo5-2026.firebasestorage.app',
    iosBundleId: 'com.example.sistemaPedido',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1yeeHFaT39H6aq0uq-s1Oyvhls3phtUU',
    appId: '1:696339704648:ios:453ef53e0e9c03606d617d',
    messagingSenderId: '696339704648',
    projectId: 'sistema-pedidos-grupo5-2026',
    storageBucket: 'sistema-pedidos-grupo5-2026.firebasestorage.app',
    iosBundleId: 'com.example.sistemaPedido',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSgMZUGmw__Dt2MReLb9fqgg3FB7-Rn8g',
    appId: '1:696339704648:web:9d6993f9582708d16d617d',
    messagingSenderId: '696339704648',
    projectId: 'sistema-pedidos-grupo5-2026',
    authDomain: 'sistema-pedidos-grupo5-2026.firebaseapp.com',
    storageBucket: 'sistema-pedidos-grupo5-2026.firebasestorage.app',
  );
}
